### ISSUE TITLE
Can't create client AttributeError: 'list' object has no attribute 'keys'

### ISSUE THREAD

**Issue by NehemiaR** [ading2210/vercel-llm-api#11] opened 2023-08-02 09:57 UTC
After pip installing properly I tried creating a client as described so I can further test, but immediatly I got an error:

import vercel_ai
client = vercel_ai.Client()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-2-756ba9d86f63>](https://localhost:8080/#) in <cell line: 2>()
      1 import vercel_ai
----> 2 client = vercel_ai.Client()

[/usr/local/lib/python3.10/dist-packages/vercel_ai.py](https://localhost:8080/#) in __init__(self, proxy)
     40 
     41     self.models = self.get_models()
---> 42     self.model_ids = list(self.models.keys())
     43     self.model_defaults = {}
     44     for model_id in self.models:

AttributeError: 'list' object has no attribute 'keys'

Checked in Anaconda and in Google Colab, same error.

**Comment by ading2210** [comment] 2023-08-02 17:44
Duplicate of #10.

**Closed as not planned by ading2210** 2023-08-02 17:44 UTC
Labels: duplicate
